Routing & Fetching
kalviumcommunity/ComicCity pull request #9
Opened 2023-05-04 07:19 UTC by pupupupupupupupupu

- Did routing 
- Fetched data from mongoDB

2023-05-04 08:08 UTC, anilgulecha commented
Arsalan, I'm very happy to see the continuous progress here. Is there a URL where I can see the app as well?

2023-05-04 08:09 UTC, anilgulecha commented
(my commend wasn't a technical review -- will let a mentor handle that. Just wanted to call out kudos on the progress)

2023-05-05 03:59 UTC, pupupupupupupupupu commented
I hosted my website on Netlify last time but I used a build folder for that
so it isn't updated yet. In some days my MVP will be finished so I'll share
the URL then. Hope it's ok.

On Thu, 4 May 2023 at 13:39, Anil Gulecha ***@***.***> wrote:

> (my commend wasn't a technical review -- will let a mentor handle that.
> Just wanted to call out kudos on the progress)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kalviumcommunity/ComicCity/pull/9#issuecomment-1534266293>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3GK34VATT4AT3N3BXXL3ULXENP2TANCNFSM6AAAAAAXVMENX4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-15 08:12 UTC, PatelNeelMahesh requested changes
You have commented code in multiple files, remove it and commit again along with additional changes added here in comments, later if you need commented code you can visit previous commits in github.

2023-05-15 08:12 UTC, PatelNeelMahesh commented on front-end/.env
> +REACT_APP_AUTH0_DOMAIN = dev-l5smjk3ej12oyjv8.us.auth0.com
`.env` file should be added in, `.gitignore` & removed from here. It contains sensitive details that should not be available here.

2023-05-15 08:12 UTC, PatelNeelMahesh commented on front-end/package.json
> +    "express": "^4.18.2",
You do not need `express` `mongodb` `mongoose` `morgan` in front-end package.json it should be in backend package.json, delete from here.

2023-05-15 08:12 UTC, PatelNeelMahesh commented on front-end/src/App.js
> +        {/* <footer>
No need to keep react component <Footer/>  in <footer></footer> tag.

2023-05-23 06:41 UTC, merged